language: php
sudo: false
php:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml

notifications:
  email: never
